- name: Harden Ubuntu based on CIS
  hosts: all
  become: yes

  tasks:

    - name: Install auditd
      apt:
        name: auditd
        state: present
        update_cache: yes

    - name: Ensure IP forwarding is disabled
      sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        state: present
        reload: yes

    - name: Configure local login banner
      copy:
        content: "Authorized uses only. All activity may be monitored and reported."
        dest: /etc/issue.net
        mode: '0644'

    - name: Ensure secure ICMP redirects are not accepted
      sysctl:
        name: net.ipv4.conf.all.secure_redirects
        value: '0'
        reload: yes

    - name: Disable IPv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        reload: yes

    - name: Collect login/logout events
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        create: yes
        line: "-w /var/log/wtmp -p wa"

    - name: Collect file deletion events
      lineinfile:
        path: /etc/audit/rules.d/audit.rules
        create: yes
        line: "-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k delete"

    - name: Set password expiration to 90 days
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   90'

    - name: Set SSH LogLevel to INFO
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LogLevel'
        line: 'LogLevel INFO'
        backup: yes
