name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t jiitak-flask-app .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop flask-app || true
          docker rm flask-app || true
          docker rmi jiitak-flask-app || true
          cd ~/app
          git pull
          docker build -t jiitak-flask-app .
          docker run -d -p 80:5000 --name flask-app jiitak-flask-app
